### ISSUE TITLE
 pidgin segfaults with both enabled jabber & loaded whatsapp

### ISSUE THREAD

**Issue by mkolchin** [davidgfnet/whatsapp-purple#245]
https://bugzilla.altlinux.org/show_bug.cgi?id=30884

**Comment by davidgfnet** [comment]
In russian :D amazing.

**Comment by dequis** [comment]
Why did you close this?

```
#0  0x00007ffff0cd682f in jpeg_consume_input () from /usr/lib64/libfreeimage.so.3
#1  0x0000003e37214c9b in jpeg_read_header () from /usr/lib64/libjpeg.so.62
```

Worrying. 

`FreeImage/Source/LibJPEG/jdapimin.c` defines jpeg_consume_input, in its own bundled libjpeg, which is probably a different version than the libjpeg linked from gdk pixbuf. This is kinda fucked up.

**Comment by davidgfnet** [comment]
Cause it's in russian and there is no explanation about the issue?

**Comment by dequis** [comment]
It's all in the backtrace. A function from libjpeg.so.62 calling one from libfreeimage.so.3.

**Comment by davidgfnet** [comment]
Do you understand the problem dx? If so feel free to sned a pull request. Many thanks for your help! :)

**Comment by dequis** [comment]
Well, like i said, it's fucked up. You could throw freeimage away (which shouldn't be bundling its own libjpeg, exporting its symbols, and conflicting with the rest of the universe), and go back to libjpeg, and add support for other file formats manually. Or use a different lib like uhhh, gd? Imagemagick?

**Comment by davidgfnet** [comment]
"it's fucked up" seems like a bad explanation. Therefore suggesting what to
do before actually understanding the problem seems to me an inappropriate
way to solve problems. I might take a look at this later.
Thanks

**Comment by dequis** [comment]
That's not the explanation. The explanation, if you really want a long version of what i already said is:

* Freeimage is bundling its own version of libjpeg that is ABI incompatible with the one installed in the system of whoever reported the bug
* gdk's `libpixbufloader-jpeg.so` links against libjpeg directly
* A function in that pixbuf loader calls `jpeg_read_header()` from `libjpeg.so.62`
* That function calls `jpeg_consume_input()`, but instead of calling the symbol in `libjpeg.so.62` like it should normally happen, it calls the one from `libfreeimage.so.3`
* Segfault happens due to incompatible interfaces.

"It's fucked up" is my conclusion, given how we can't do anything with the fact that freeimage is bundling libjpeg.

**Comment by davidgfnet** [comment]
Still many questions come up to my mind:
- Why is the dynamic loader linking freeimage/gdk to the same libjpeg
version? If the answer is: because they have the same library name in the
import table then my understanding of it is that they should have ABI
compatible interfaces, right?
- Is it possible that on other Linux distros both libraries are using the
same jpeg lib backend (and therefore there is no problem at all)?

This sounds very weird to me.
The reason to use freeimage it's not just the compression, but scaling,
cropping and the ability to import PNG/BMP/* images, which is great.

Cheers

**Comment by glebfm** [comment]
I'm the one who reported this bug to ALT Bugzilla.

> At #0-#1 we see libjpeg trying to call it's own function, but
> accidentally called function is from other library. I suppose that
> libjpeg and libfreeimage should not be ever loaded to same namespace.

Problem is that libfreeimage is not dynamically linked with libjpeg, it
bundles it's own version. Furthermore, it bundles libpng, libtiff, zlib
and libraw. Such approach causes problems like this bug.

Some distributions (including ALT) made some work to build libfreeimage
without bundled png, tiff and zlib. But it's not so easy in case of jpeg,
because libfreeimage uses jpeg's private headers.

I will fix this for ALT, but it may explode again.

**Comment by dequis** [comment]
@davidgfnet You could reopen the bug now that you have a translation of the description :P

**Comment by davidgfnet** [comment]
OK, but seems to me platform-specific. So... It's not likely to get fixed by me
