### ISSUE TITLE
crash when invite a buddy to group chat

### ISSUE THREAD

**Issue by tempforreport** [davidgfnet/whatsapp-purple#300]
here pidgin -d output
```
(18:48:14) GLib: g_strsplit: assertion 'string != NULL' failed
Pidgin 2.10.11 has segfaulted and attempted to dump a core file.
This is a bug in the software and has happened through
no fault of your own.

If you can reproduce the crash, please notify the developers
by reporting a bug at:
http://developer.pidgin.im/simpleticket/

Please make sure to specify what you were doing at the time
and post the backtrace from the core file.  If you do not know
how to get the backtrace, please read the instructions at
http://developer.pidgin.im/wiki/GetABacktrace
Aborted
```
bt log:
```
#0  0x00007fffde7cfdc3 in waprpl_chat_invite (gc=0x5555560d7380, id=1424091262, message=0x0, name=0x555556212730 "p_number_of_invited_buddy") at wa_purple.cc:1208
        convo = 0x555555d1a420
        admins = 0x0
        me = 0x555555995e60 "my_number"
        imadmin = 0
        p = 0x0
        chat_id = 0x555555d72e00 "my_number-1424091262"
        wconn = 0x5555560d7520
        acct = 0x555555995ea0
        ch = 0x555555d72ee0
        hasht = 0x555555ce4360
        adminl = 0x0
#1  0x00007ffff5275dd6 in serv_chat_invite (gc=0x5555560d7380, id=id@entry=1424091262, message=message@entry=0x7ffff6a51384 "", 
    name=name@entry=0x555556212730 "p_number_of_invited_buddy") at /tmp/buildd/pidgin-2.10.11/./libpurple/server.c:500
        prpl = <optimized out>
        prpl_info = 0x7fffde9f2500 <prpl_info>
        conv = 0x555555d1a420
        buffy = 0x0
#2  0x00005555555b0924 in do_invite (w=<optimized out>, resp=<optimized out>, info=0x5555562d4e90) at /tmp/buildd/pidgin-2.10.11/./pidgin/gtkconv.c:756
        buddy = 0x555556212730 "p_number_of_invited_buddy"
        message = 0x7ffff6a51384 ""
        conv = 0x555555d1a420
#3  0x00007ffff5844568 in g_cclosure_marshal_VOID(int0_t, void) () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#4  0x00007ffff5842504 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#5  0x00007ffff585bfa7 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#6  0x00007ffff585c8ff in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#7  0x00007ffff5842504 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#8  0x00007ffff585bfa7 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#9  0x00007ffff585c8ff in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#10 0x00007ffff6773225 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#11 0x00007ffff5842504 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#12 0x00007ffff585bfa7 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#13 0x00007ffff585c8ff in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#14 0x00007ffff6772119 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#15 0x00007ffff6818a7f in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#16 0x00007ffff58422d5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#17 0x00007ffff5853f32 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#18 0x00007ffff585c1a5 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#19 0x00007ffff585c8ff in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#20 0x00007ffff692fecc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#21 0x00007ffff68171c4 in gtk_propagate_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#22 0x00007ffff681765b in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#23 0x00007ffff648abbc in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
No symbol table info available.
#24 0x00007ffff556cc3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#25 0x00007ffff556cf20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#26 0x00007ffff556d242 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#27 0x00007ffff68165d7 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#28 0x000055555558f557 in main (argc=1, argv=0x7fffffffdea8) at /tmp/buildd/pidgin-2.10.11/./pidgin/gtkmain.c:937
        opt_help = -17616
        opt_version = 1436178432
        opt_config_dir_arg = 0x0
        accounts = 0x0
        sigset = {__val = {82950, 0 <repeats 15 times>}}
        errmsg = '\000' <repeats 360 times>...
        signal_channel = 0x0
        signal_status = G_IO_STATUS_ERROR
        error = 0x0
        opt = 0
        debug_enabled = 80
        active_accounts = 0x0
        long_options = {{name = 0x55555562c2e7 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55555561a779 "debug", has_arg = 0, flag = 0x0, val = 100}, {
            name = 0x5555556282d1 "force-online", has_arg = 0, flag = 0x0, val = 102}, {name = 0x55555561c2fa "help", has_arg = 0, flag = 0x0, val = 104}, {
            name = 0x55555562817d "login", has_arg = 2, flag = 0x0, val = 108}, {name = 0x5555556282de "multiple", has_arg = 0, flag = 0x0, val = 109}, {
            name = 0x5555556282e7 "nologin", has_arg = 0, flag = 0x0, val = 110}, {name = 0x55555562c2fa "session", has_arg = 1, flag = 0x0, val = 115}, {
            name = 0x55555561eb7a "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55555562c2f0 "display", has_arg = 1, flag = 0x0, val = 68}, {
            name = 0x555555628e53 "sync", has_arg = 0, flag = 0x0, val = 83}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
```

**Comment by vmorenomarin** [comment]
I had the same problem. It was fixed when purple-whatsapp was updated from 0.8.4 to 0.8.5.

**Comment by tempforreport** [comment]
still persist 0.8.5.

**Comment by JayFoxRox** [comment]
admins = NULL: https://github.com/davidgfnet/whatsapp-purple/commit/3f0370b989dbdacfd497f307ffc86db301039757 was supposed to fix it (Changed from 0.8.4 to 0.8.5).

Are you 100% sure you are using the latest version of whatsapp-purple? Try removing whatsapp-purple, then starting pidgin and check if your whatsapp account isn't available anymore (to make sure it is completly removed), then reinstall whatsapp-purple (from git would be best - alternatively 0.8**.5**) and retry.

**Comment by tempforreport** [comment]
completly removed, build from latest source, still same.

**Comment by davidgfnet** [comment]
Try to delete all you accounts (.purple directory) and start from scratch.
Might be some values stored in the blist.xml file are garbage. It happened
to me.

**Comment by tempforreport** [comment]
removing blist.xml solved the problem. thanks.
